//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldCupWPF.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorldCupWPF.Localization.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odustani.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postavi kao omiljeni tim.
        /// </summary>
        internal static string btnFavorite {
            get {
                return ResourceManager.GetString("btnFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregled omiljenih.
        /// </summary>
        internal static string btnFavoriteTeamOverview {
            get {
                return ResourceManager.GetString("btnFavoriteTeamOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string btnOK {
            get {
                return ResourceManager.GetString("btnOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregled.
        /// </summary>
        internal static string btnOverview {
            get {
                return ResourceManager.GetString("btnOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregled protivnih.
        /// </summary>
        internal static string btnRivalTeamOverview {
            get {
                return ResourceManager.GetString("btnRivalTeamOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postavke.
        /// </summary>
        internal static string btnSettings {
            get {
                return ResourceManager.GetString("btnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        internal static string cbOffline {
            get {
                return ResourceManager.GetString("cbOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapetan.
        /// </summary>
        internal static string lblCaptain {
            get {
                return ResourceManager.GetString("lblCaptain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reprezentacija.
        /// </summary>
        internal static string lblChampionship {
            get {
                return ResourceManager.GetString("lblChampionship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod drzave.
        /// </summary>
        internal static string lblCountryCode {
            get {
                return ResourceManager.GetString("lblCountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izjednacenja.
        /// </summary>
        internal static string lblDraws {
            get {
                return ResourceManager.GetString("lblDraws", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omiljeni tim.
        /// </summary>
        internal static string lblFavoriteTeam {
            get {
                return ResourceManager.GetString("lblFavoriteTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj matcheva.
        /// </summary>
        internal static string lblGamesPlayed {
            get {
                return ResourceManager.GetString("lblGamesPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Golovi.
        /// </summary>
        internal static string lblGoals {
            get {
                return ResourceManager.GetString("lblGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Golovi protiv.
        /// </summary>
        internal static string lblGoalsAgainst {
            get {
                return ResourceManager.GetString("lblGoalsAgainst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Golovi za.
        /// </summary>
        internal static string lblGoalsFor {
            get {
                return ResourceManager.GetString("lblGoalsFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jezik.
        /// </summary>
        internal static string lblLanguage {
            get {
                return ResourceManager.GetString("lblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gubitci.
        /// </summary>
        internal static string lblLosses {
            get {
                return ResourceManager.GetString("lblLosses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregled statistike.
        /// </summary>
        internal static string lblOverview {
            get {
                return ResourceManager.GetString("lblOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poeni.
        /// </summary>
        internal static string lblPoints {
            get {
                return ResourceManager.GetString("lblPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezolucija.
        /// </summary>
        internal static string lblResolution {
            get {
                return ResourceManager.GetString("lblResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezultat.
        /// </summary>
        internal static string lblResult {
            get {
                return ResourceManager.GetString("lblResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protivni tim.
        /// </summary>
        internal static string lblRivalTeam {
            get {
                return ResourceManager.GetString("lblRivalTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj dresa.
        /// </summary>
        internal static string lblShirtNumber {
            get {
                return ResourceManager.GetString("lblShirtNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postavke.
        /// </summary>
        internal static string lblSoccerBoardSettings {
            get {
                return ResourceManager.GetString("lblSoccerBoardSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobjede.
        /// </summary>
        internal static string lblWins {
            get {
                return ResourceManager.GetString("lblWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zuti kartoni.
        /// </summary>
        internal static string lblYellowCards {
            get {
                return ResourceManager.GetString("lblYellowCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Cup pocetna.
        /// </summary>
        internal static string MainWindow {
            get {
                return ResourceManager.GetString("MainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregled igraca.
        /// </summary>
        internal static string PlayerViewTitle {
            get {
                return ResourceManager.GetString("PlayerViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1024x768.
        /// </summary>
        internal static string rb1024 {
            get {
                return ResourceManager.GetString("rb1024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 800x600.
        /// </summary>
        internal static string rb800 {
            get {
                return ResourceManager.GetString("rb800", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hrvatski.
        /// </summary>
        internal static string rbCroatian {
            get {
                return ResourceManager.GetString("rbCroatian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engleski.
        /// </summary>
        internal static string rbEnglish {
            get {
                return ResourceManager.GetString("rbEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cijeli zaslon.
        /// </summary>
        internal static string rbFullScreen {
            get {
                return ResourceManager.GetString("rbFullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muški.
        /// </summary>
        internal static string rbMen {
            get {
                return ResourceManager.GetString("rbMen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žene.
        /// </summary>
        internal static string rbWomen {
            get {
                return ResourceManager.GetString("rbWomen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregled statistike.
        /// </summary>
        internal static string ScoreOverviewBoard {
            get {
                return ResourceManager.GetString("ScoreOverviewBoard", resourceCulture);
            }
        }
    }
}
